version: "3.8"

services:
  express_app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "8080"
      DATABASE_URL: "postgresql://neondb_owner:npg_4scgjwIS1onG@ep-plain-glitter-a47r5fwv-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      JWT_SECRET: "my_jwt_secret_key"
      JWT_EXPIRES_IN: "7d"
    ports:
      - "8080:8080"
